import { useState } from "react";
import type { GameLevel } from "../data/projects";
import type { Edge } from "@xyflow/react";

interface ExportModalProps {
  level: GameLevel;
  onClose: () => void;
}

type ExportFormat = "wwise" | "fmod" | "json" | "markdown";

function generateWwiseTemplate(level: GameLevel): string {
  const lines: string[] = [];
  lines.push(`// ═══════════════════════════════════════════════════════════════════`);
  lines.push(`// Wwise Adaptive Music Template — ${level.name}`);
  lines.push(`// "${level.subtitle}"`);
  lines.push(`// Generated by Score Canvas — ${new Date().toISOString().split("T")[0]}`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════`);
  lines.push(``);
  lines.push(`// ─── Music Switch Container: ${level.name} ──────────────────────`);
  lines.push(`//`);
  lines.push(`// Hierarchy:`);
  lines.push(`//   Interactive Music Hierarchy`);
  lines.push(`//     └─ Music Switch Container: MSC_${level.id.replace(/-/g, "_")}`);

  const musicStates = level.nodes.filter((n) => n.type === "musicState");
  const parameters = level.nodes.filter((n) => n.type === "parameter");
  const stingers = level.nodes.filter((n) => n.type === "stinger");

  musicStates.forEach((node) => {
    const d = node.data as Record<string, unknown>;
    lines.push(`//         ├─ Music Playlist Container: MPC_${String(d.label).replace(/[^a-zA-Z0-9]/g, "_")}`);
    lines.push(`//         │    Asset: ${String(d.asset || "unassigned")}`);
    lines.push(`//         │    Looping: ${d.looping ? "Yes (Infinite)" : "Play Once"}`);
  });

  lines.push(`//`);
  lines.push(`// ─── States ────────────────────────────────────────────────────────`);
  lines.push(`//`);
  lines.push(`// State Group: SG_${level.id.replace(/-/g, "_")}_MusicState`);
  musicStates.forEach((node) => {
    const d = node.data as Record<string, unknown>;
    lines.push(`//   State: ${String(d.label).replace(/\s/g, "_")}`);
  });

  if (parameters.length > 0) {
    lines.push(`//`);
    lines.push(`// ─── Game Parameters (RTPC) ────────────────────────────────────────`);
    parameters.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`//`);
      lines.push(`//   RTPC: ${d.paramName}`);
      lines.push(`//     Range: ${d.minValue} — ${d.maxValue} (Default: ${d.defaultValue})`);
      lines.push(`//     Description: ${d.description}`);
    });
  }

  lines.push(`//`);
  lines.push(`// ─── Transitions ────────────────────────────────────────────────────`);
  level.edges.forEach((edge) => {
    const src = level.nodes.find((n) => n.id === edge.source);
    const tgt = level.nodes.find((n) => n.id === edge.target);
    if (src && tgt) {
      const srcLabel = String((src.data as Record<string, unknown>).label);
      const tgtLabel = String((tgt.data as Record<string, unknown>).label);
      const condition = (edge as Edge & { label?: string }).label || "—";
      lines.push(`//   ${srcLabel} → ${tgtLabel}  [${condition}]`);
    }
  });

  if (stingers.length > 0) {
    lines.push(`//`);
    lines.push(`// ─── Stingers ──────────────────────────────────────────────────────`);
    stingers.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`//   Stinger: ${d.label}`);
      lines.push(`//     Trigger: ${d.trigger}  |  Asset: ${d.asset}  |  Priority: ${d.priority}`);
    });
  }

  const events = level.nodes.filter((n) => n.type === "event");
  if (events.length > 0) {
    lines.push(`//`);
    lines.push(`// ─── Game Events ───────────────────────────────────────────────────`);
    events.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`//   Event: ${d.label}`);
      lines.push(`//     Type: ${d.eventType}  |  Blueprint: ${d.blueprintRef}`);
      lines.push(`//     Description: ${d.description}`);
    });
  }

  // Director notes
  const notedNodes = level.nodes.filter((n) => (n.data as Record<string, unknown>).directorNote);
  if (notedNodes.length > 0) {
    lines.push(`//`);
    lines.push(`// ─── Director Notes ────────────────────────────────────────────────`);
    notedNodes.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`//   [${d.label}]: ${d.directorNote}`);
    });
  }

  lines.push(`//`);
  lines.push(`// ─── Music Assets Required ──────────────────────────────────────────`);
  level.assets.forEach((a) => {
    lines.push(`//   ${a.filename}  (${a.category}, ${a.duration}, ${a.bpm > 0 ? a.bpm + " BPM" : "ambient"}, ${a.key})`);
  });

  lines.push(`//`);
  lines.push(`// ═══════════════════════════════════════════════════════════════════`);
  return lines.join("\n");
}

function generateFmodTemplate(level: GameLevel): string {
  const lines: string[] = [];
  lines.push(`# FMOD Studio — Adaptive Music Template`);
  lines.push(`# Level: ${level.name} — "${level.subtitle}"`);
  lines.push(`# Generated by Score Canvas — ${new Date().toISOString().split("T")[0]}`);
  lines.push(``);
  lines.push(`## Event: event:/Music/${level.id.replace(/-/g, "_")}`);
  lines.push(``);
  lines.push(`### Timeline Instruments`);

  const musicStates = level.nodes.filter((n) => n.type === "musicState");
  musicStates.forEach((node) => {
    const d = node.data as Record<string, unknown>;
    lines.push(`- Multi Instrument: ${d.label}`);
    lines.push(`  - Asset: ${d.asset || "unassigned"}`);
    lines.push(`  - Looping: ${d.looping ? "Yes" : "No"}`);
  });

  lines.push(``);
  lines.push(`### Parameters`);
  level.nodes.filter((n) => n.type === "parameter").forEach((node) => {
    const d = node.data as Record<string, unknown>;
    lines.push(`- ${d.paramName}: ${d.minValue}–${d.maxValue} (default: ${d.defaultValue})`);
    lines.push(`  ${d.description}`);
  });

  lines.push(``);
  lines.push(`### Transition Rules`);
  level.edges.forEach((edge) => {
    const src = level.nodes.find((n) => n.id === edge.source);
    const tgt = level.nodes.find((n) => n.id === edge.target);
    if (src && tgt) {
      const srcLabel = String((src.data as Record<string, unknown>).label);
      const tgtLabel = String((tgt.data as Record<string, unknown>).label);
      const condition = (edge as Edge & { label?: string }).label || "—";
      lines.push(`- ${srcLabel} → ${tgtLabel} [${condition}]`);
    }
  });

  return lines.join("\n");
}

function generateJSON(level: GameLevel): string {
  const exportData = {
    meta: {
      generator: "Score Canvas",
      version: "0.1.0",
      exportDate: new Date().toISOString(),
      level: level.name,
      subtitle: level.subtitle,
      region: level.region,
    },
    musicStates: level.nodes.filter((n) => n.type === "musicState").map((n) => ({
      id: n.id,
      ...(n.data as Record<string, unknown>),
    })),
    transitions: level.nodes.filter((n) => n.type === "transition").map((n) => ({
      id: n.id,
      ...(n.data as Record<string, unknown>),
    })),
    parameters: level.nodes.filter((n) => n.type === "parameter").map((n) => ({
      id: n.id,
      ...(n.data as Record<string, unknown>),
    })),
    stingers: level.nodes.filter((n) => n.type === "stinger").map((n) => ({
      id: n.id,
      ...(n.data as Record<string, unknown>),
    })),
    events: level.nodes.filter((n) => n.type === "event").map((n) => ({
      id: n.id,
      ...(n.data as Record<string, unknown>),
    })),
    connections: level.edges.map((e) => ({
      from: e.source,
      to: e.target,
      condition: (e as Edge & { label?: string }).label || null,
    })),
    assets: level.assets,
  };
  return JSON.stringify(exportData, null, 2);
}

function generateMarkdown(level: GameLevel): string {
  const lines: string[] = [];
  lines.push(`# Adaptive Music Design — ${level.name}`);
  lines.push(`> *${level.subtitle}* | ${level.region}`);
  lines.push(`>`);
  lines.push(`> Generated by Score Canvas — ${new Date().toISOString().split("T")[0]}`);
  lines.push(``);
  lines.push(`## Music States`);
  lines.push(`| State | Asset | Intensity | Looping | Stems |`);
  lines.push(`|-------|-------|-----------|---------|-------|`);

  level.nodes.filter((n) => n.type === "musicState").forEach((node) => {
    const d = node.data as Record<string, unknown>;
    const stems = (d.stems as string[]).join(", ");
    lines.push(`| ${d.label} | \`${d.asset || "—"}\` | ${d.intensity}/100 | ${d.looping ? "Yes" : "No"} | ${stems} |`);
  });

  const params = level.nodes.filter((n) => n.type === "parameter");
  if (params.length > 0) {
    lines.push(``);
    lines.push(`## Game Parameters (RTPC)`);
    lines.push(`| Parameter | Range | Default | Description |`);
    lines.push(`|-----------|-------|---------|-------------|`);
    params.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`| \`${d.paramName}\` | ${d.minValue}–${d.maxValue} | ${d.defaultValue} | ${d.description} |`);
    });
  }

  lines.push(``);
  lines.push(`## Transitions`);
  lines.push(`| From | To | Condition |`);
  lines.push(`|------|----|-----------|`);
  level.edges.forEach((edge) => {
    const src = level.nodes.find((n) => n.id === edge.source);
    const tgt = level.nodes.find((n) => n.id === edge.target);
    if (src && tgt) {
      const srcLabel = String((src.data as Record<string, unknown>).label);
      const tgtLabel = String((tgt.data as Record<string, unknown>).label);
      const condition = (edge as Edge & { label?: string }).label || "—";
      lines.push(`| ${srcLabel} | ${tgtLabel} | ${condition} |`);
    }
  });

  const stingers = level.nodes.filter((n) => n.type === "stinger");
  if (stingers.length > 0) {
    lines.push(``);
    lines.push(`## Stingers`);
    lines.push(`| Name | Trigger | Asset | Priority |`);
    lines.push(`|------|---------|-------|----------|`);
    stingers.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`| ${d.label} | \`${d.trigger}\` | \`${d.asset}\` | ${d.priority} |`);
    });
  }

  const events = level.nodes.filter((n) => n.type === "event");
  if (events.length > 0) {
    lines.push(``);
    lines.push(`## Game Events`);
    lines.push(`| Event | Type | Blueprint | Description |`);
    lines.push(`|-------|------|-----------|-------------|`);
    events.forEach((node) => {
      const d = node.data as Record<string, unknown>;
      lines.push(`| ${d.label} | ${d.eventType} | \`${d.blueprintRef}\` | ${d.description} |`);
    });
  }

  lines.push(``);
  lines.push(`## Required Assets`);
  lines.push(`| Filename | Type | Duration | BPM | Key |`);
  lines.push(`|----------|------|----------|-----|-----|`);
  level.assets.forEach((a) => {
    lines.push(`| \`${a.filename}\` | ${a.category} | ${a.duration} | ${a.bpm > 0 ? a.bpm : "—"} | ${a.key} |`);
  });

  return lines.join("\n");
}

export function ExportModal({ level, onClose }: ExportModalProps) {
  const [format, setFormat] = useState<ExportFormat>("wwise");

  const generators: Record<ExportFormat, (l: GameLevel) => string> = {
    wwise: generateWwiseTemplate,
    fmod: generateFmodTemplate,
    json: generateJSON,
    markdown: generateMarkdown,
  };

  const output = generators[format](level);
  const fileExtensions: Record<ExportFormat, string> = { wwise: "txt", fmod: "md", json: "json", markdown: "md" };

  const handleDownload = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `scorecanvas_${level.id}_${format}.${fileExtensions[format]}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-[#0d0d1a] border border-canvas-accent rounded-xl shadow-2xl w-[750px] max-h-[80vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-canvas-accent">
          <div>
            <h2 className="text-sm font-bold text-canvas-text">Export Middleware Template</h2>
            <p className="text-[10px] text-canvas-muted font-mono mt-0.5">{level.name} — {level.nodes.length} nodes, {level.assets.length} assets</p>
          </div>
          <button onClick={onClose} className="text-canvas-muted hover:text-canvas-text text-lg leading-none">&times;</button>
        </div>

        {/* Format selector */}
        <div className="flex items-center gap-2 px-5 py-2 border-b border-canvas-accent/50">
          {(["wwise", "fmod", "json", "markdown"] as ExportFormat[]).map((f) => (
            <button
              key={f}
              onClick={() => setFormat(f)}
              className={`text-[10px] font-mono uppercase px-3 py-1.5 rounded transition-colors ${
                format === f
                  ? "bg-canvas-highlight/20 text-canvas-highlight border border-canvas-highlight/30"
                  : "text-canvas-muted hover:text-canvas-text border border-canvas-accent"
              }`}
            >
              {f === "wwise" ? "Wwise Template" : f === "fmod" ? "FMOD Template" : f === "json" ? "JSON Data" : "Markdown Doc"}
            </button>
          ))}
          <div className="flex-1" />
          <button
            onClick={handleCopy}
            className="text-[10px] font-mono text-canvas-muted hover:text-canvas-text px-2 py-1 rounded border border-canvas-accent hover:border-canvas-highlight/50 transition-colors"
          >
            Copy
          </button>
          <button
            onClick={handleDownload}
            className="text-[10px] font-mono text-white bg-canvas-highlight hover:bg-canvas-highlight/80 px-3 py-1 rounded transition-colors"
          >
            Download
          </button>
        </div>

        {/* Output */}
        <div className="overflow-auto flex-1 p-4">
          <pre className="text-[11px] font-mono text-canvas-text/90 leading-relaxed whitespace-pre-wrap">{output}</pre>
        </div>
      </div>
    </div>
  );
}
